### ISSUE TITLE
update login

### ISSUE THREAD

**Issue by aerioeus** [acloudfan/REST-API-Course#1]
i receive the following error when I start index.js 

node:13972) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using
MongoClient.connect with auth credentials.

**Comment by acloudfan** [comment]
Hi I have updated the code and you should not see the warning anymore.

Regards, Raj
